repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.27.0
    hooks:
      - id: semgrep
        args:
          [
            "--config",
            "https://semgrep.dev/p/python",
            "--config",
            "https://semgrep.dev/p/eslint",
            "--config",
            "https://semgrep.dev/p/django",
            "--config",
            "https://semgrep.dev/p/insecure-transport",
            "--config",
            "https://semgrep.dev/p/sql-injection",
            "--config",
            "https://semgrep.dev/p/r2c-best-practices",
            "--config",
            "https://semgrep.dev/p/r2c-security-audit",
            "--config",
            "https://semgrep.dev/p/headless-browser",
            "--config",
            "https://semgrep.dev/p/cwe-top-25",
            "--config",
            "https://semgrep.dev/p/owasp-top-ten",
            "--config",
            "https://semgrep.dev/p/jwt",
            "--config",
            "https://semgrep.dev/p/xss",
            "--config",
            "https://semgrep.dev/p/secrets",
            "--config",
            "https://semgrep.dev/p/r2c-bug-scan",
            "--config",
            "https://semgrep.dev/p/bandit",
            "--error",
            "--skip-unknown-extensions",
          ]
