repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.5"
    hooks:
      - id: bandit
  - repo: https://github.com/returntocorp/semgrep
    rev: "v1.27.0"
    hooks:
      - id: semgrep
        args:
          [
            "--config",
            "https://semgrep.dev/p/eslint",
            "--config",
            "https://semgrep.dev/p/django",
            "--error",
            "--skip-unknown-extensions",
          ]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["-rn", "-sn"]
