[tool.isort]
py_version=39
skip = [
    '.bzr',
    '.direnv',
    '.eggs',
    '.git',
    '.hg',
    '.mypy_cache',
    '.nox',
    '.pants.d',
    '.svn',
    '.tox', 
    '.venv',
    '.env',
    '__pypackages__',
    '_build',
    'buck-out',
    'build',
    'dist',
    'node_modules',
    'venv',
    'env',
    'package'
]
profile = 'hug'
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'DJANGO', 'FIRSTPARTY', 'LOCALFOLDER']
known_third_party = [
    'allauth',
    'allauth.account',
    'bootstrap3',
    'bootstrapform',
    'captcha',
    'censo',
    'ckeditor',
    'colorful',
    'corsheaders',
    'debug_toolbar',
    'localflavor',
    'nested_admin',
    'oauth2_provider',
    'storages',
    'two_factor',
    'webpack_loader',
    'webpush',
    'xlrd',
    'xlsxwriter',
    'pytz',
    'playhouse',
    'dateutil'
]
known_django = [
    'django',
    'django_crontab',
    'django_filters',
    'django_gulp',
    'django_json_widget',
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'django_ses',
    'rest_framework',
    'rest_framework.authtoken',
]
known_first_party = [
    'market_transaction',
    'financier_models',
    'destacame_models',
    'bifrost',
    'accounts',
    'addresses',
    'basic',
    'bills',
    'business_intelligence',
    'caser',
    'censo',
    'commons',
    'communications',
    'communicator_tracking',
    'contact_points',
    'coupons',
    'debts',
    'destacame',
    'destacame_app',
    'emailer',
    'external_api_component',
    'financial_dock',
    'front',
    'modal_news',
    'news',
    'offers',
    'payments',
    'pdf',
    'pixel',
    'providers',
    'report_control',
    'report_manager',
    'saving',
    'scoring',
    'serverless',
    'services_aws',
    'smart_selects',
    'stats',
    'subscription',
    'tagger',
    'tools'
]
known_local_folder = [
    'controllers',
    'settings',
    'utils',
    'models',
    'decorators',
]