# Generated by Django 4.0.1 on 2022-01-11 04:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_backend.bus')),
            ],
            options={
                'unique_together': {('bus', 'sequence_number')},
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_backend.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_backend.route')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_backend.seat')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_backend.trip')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='from_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_station', to='bus_backend.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='to_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_station', to='bus_backend.station'),
        ),
    ]
