# Generated by Django 4.0.1 on 2022-01-11 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='manufacturer',
            field=models.CharField(default='Yutong', max_length=255),
        ),
        migrations.AddField(
            model_name='bus',
            name='type',
            field=models.CharField(default='Modelo FSO 1701 con retardador incorporado', max_length=255),
        ),
        migrations.AlterField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
