# Generated by Django 4.0.1 on 2022-01-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_backend', '0002_bus_manufacturer_bus_type_alter_bus_driver'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('trip', 'seat')},
        ),
    ]
