# Generated by Django 4.0.1 on 2022-01-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_backend', '0006_alter_bus_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='type',
        ),
    ]
