# Generated by Django 4.0.1 on 2022-01-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_backend', '0007_remove_bus_manufacturer_remove_bus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='entertainment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='extra_leg_room',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='usb',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='wifi',
            field=models.BooleanField(default=True),
        ),
    ]
