# Generated by Django 4.0.1 on 2022-01-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_backend', '0008_bus_entertainment_bus_extra_leg_room_bus_usb_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('from_station', 'to_station')},
        ),
    ]
